enum QueryKeys {
	GET_LESSON = 'GET_LESSON',
	GET_LESSONS = 'GET_LESSONS',
	GET_CONCEPTS = 'GET_CONCEPTS',
	GET_TECHSTACKS = 'GET_TECHSTACKS',
	GET_EXAM = 'GET_EXAM',
	GET_COURSES_SCORES = 'GET_COURSES_SCORES',
}

export default QueryKeys;
